SET DEFINE OFF;
--SQL Statement which produced this data:
--
--  SELECT 
--     ROWID, T.INTERFACE_ID, T.FILE_NAME, T.SP_NAME, 
--     T.SP_STG_STRING1, T.SP_REF_STRING1, T.SP_OPERATION, 
--     T.STATUS, T.STG_TABLE, T.SEQUENCE_ID, 
--     T.IS_DEPENDENT, T.OUTPUT_FILE_NAME, T.TEMP_TBL_QUERY, 
--     T.ENV
--  FROM IIW.TBL_ETL_ROUTE_DETAILS T
--
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME, ENV)
 Values
   ('ABI_MULE_PKG_PRD_DEL', 'INPUT_FILENAME', 'SP_MULE_PKG_PRD_DEL', 
    'C', 'REF_CUR_PKG_PRD', 87, 'N', 'CUR_PKG_PRD_DEL', 'DEV');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_PHF_LOC_LOAD', 'INPUT_FILENAME', 'SP_MULE_PHF_LOC_LOAD', 
    'C', 'MDM_Labatt_Ref', 86, 'N', 'CUR_PHF_LOC');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, SP_REF_STRING1, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_PAY_GRP_LOAD', 'V_T710', 'SP_DETECT_DELTA', 'SELECT  distinct slgrp as pay_grp_code , ''N''  as pay_grp_deleted
FROM  MDMETL.stage_so_v_t710
WHERE  sysdate BETWEEN begda AND endda
And slgrp is not null', 
    'SELECT  PAY_GRP_CODE, ''N''  as pay_grp_deleted FROM  WHSUSR.REF_CUR_PAY_GRP@MDMP.WORLD@WHSUSR WHERE REF_CUR_PAY_GRP.PAY_GRP_DELETED = ''N''', 'C', 'STAGE_SO_V_T710', 30, 
    'Y', 'CUR_PAY_GRP');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, SP_REF_STRING1, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_EMP_GRP_LOAD', 'T501T', 'SP_DETECT_DELTA', 'SELECT  LTRIM(RTRIM(a.persg)) as PERSG
   ,LTRIM(RTRIM(NVL(b.ptext, ''NO VALUE''))) as PTEXT
   ,LTRIM(RTRIM(NVL(c.ptext, ''NO VALUE''))) as PTEXT_FR,
   ''N'' as emp_grp_deleted
FROM MDMETL.stage_so_t501t c, MDMETL.stage_so_t501t b, MDMETL.stage_so_t501 a
WHERE a.persg = b.persg (+) and nvl(b.sprsl (+),''Z'') = ''E''
AND  a.persg = c.persg (+) and nvl(c.sprsl (+),''Z'') = ''F''', 
    'SELECT  REF_CUR_EMP_GRP.EMP_GRP_ID as EMP_GRP_ID,REF_CUR_EMP_GRP.EMP_GRP_NAME as EMP_GRP_NAME, REF_CUR_EMP_GRP.EMP_GRP_FR_NAME as EMP_GRP_FR_NAME,
''N'' as emp_grp_deleted
 FROM WHSUSR.REF_CUR_EMP_GRP@MDMP.WORLD@WHSUSR
where EMP_GRP_DELETED=''N''', 'C', 'STAGE_SO_T501T', 27, 
    'Y', 'CUR_EMP_GRP');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, SP_REF_STRING1, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_PRS_ACT_LOAD', 'T530T', 'SP_DETECT_DELTA', 'select distinct t1.MASSN as PRS_ACT_CODE, t1.MNTXT as PRS_ACT_DESC, t2.MNTXT as PRS_ACT_FDESC, ''N'' as  PRS_ACT_deleted
from MDMETL.STAGE_SO_T530T t1, MDMETL.STAGE_SO_T530T t2
where t1.massn = t2.massn
and t1.sprsl = ''E''
and (t1.massn like (''Z%'') or t1.massn like (''D%''))
and t2.sprsl = ''F''
and (t2.massn like (''Z%'') or t1.massn like (''D%''))', 
    'SELECT REF_CUR_PRS_ACT.PRS_ACT_CODE as PRS_ACT_CODE,REF_CUR_PRS_ACT.PRS_ACT_DESC as PRS_ACT_DESC, REF_CUR_PRS_ACT.PRS_ACT_FDESC as PRS_ACT_FDESC,
 ''N'' as  PRS_ACT_deleted
  FROM WHSUSR.REF_CUR_PRS_ACT@MDMP.WORLD@WHSUSR
where PRS_ACT_DELETED=''N''', 'C', 'STAGE_SO_T530T', 29, 
    'Y', 'CUR_PRS_ACT');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, SP_REF_STRING1, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_PAY_GRP_DEL', 'V_T001P', 'SP_DETECT_DELTA', 'SELECT REF_CUR_PAY_GRP.PAY_GRP_CODE , ''Y'' AS DEL_FLAG
FROM
 WHSUSR.REF_CUR_PAY_GRP@MDMP.WORLD@WHSUSR  
WHERE
 REF_CUR_PAY_GRP.PAY_GRP_DELETED <> ''Y''', 
    'SELECT  distinct slgrp AS SLGRP , ''Y'' AS DEL_FLAG
FROM  MDMETL.stage_so_v_t710
WHERE  sysdate BETWEEN begda AND endda
And slgrp is not null', 'C', 'STAGE_SO_V_T001P', 31, 
    'Y', 'CUR_PAY_GRP_DEL');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, SP_REF_STRING1, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_POS_SHARP_DEL', 'V_528B_C', 'SP_DETECT_DELTA', 'SELECT DISTINCT POS_ID  , ''Y'' AS DEL_FLAG
FROM WHSUSR.REF_CUR_POS_SHARP@MDMP.WORLD@WHSUSR
WHERE POS_DELETED <> ''Y''
', 
    'SELECT distinct  plans as PLANS , ''Y'' AS DEL_FLAG
FROM MDMETL.stage_so_v_528b_c WHERE otype = ''S''', 'C', 'STAGE_SO_V_528B_C ', 32, 
    'Y', 'CUR_POS_SHARP_DEL');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_POS_SHARP_LOAD', 'V_T529U', 'SP_MULE_POS_SHARP_LOAD', 
    'C', 'STAGE_SO_V_T529U', 33, 'N', 'CUR_POS_SHARP');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_PRSN_ADDR_SHARP_LOAD', 'PA0006', 'SP_MULE_PRSN_ADDR_SHARP_LOAD', 
    'C', 'STAGE_SO_PA0006', 36, 'N', 'CUR_PRSN_ADDR_SHARP');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_T529T', 'T529T', 'SP_FILENAME', 
    'C', 'STAGE_SO_T529T', 45, 'N', 'CUR_FILENAME');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_T005S', 'T005S', 'SP_FILENAME', 
    'C', 'STAGE_SO_T005S', 48, 'N', 'CUR_FILENAME');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_T591S', 'T591S', 'SP_FILENAME', 
    'C', 'STAGE_SO_T591S', 51, 'N', 'CUR_FILENAME');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_T500L', 'T500L', 'SP_FILENAME', 
    'C', 'STAGE_SO_T500L', 62, 'N', 'CUR_FILENAME');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_PAY_STRCT_LOAD', 'T710', 'SP_STORE_SQUERY_IN_TEMP', '
select 
 PAY_STRCT_CODE,Pay_strct_name ,PAY_STRCT_LW_RANGE, 
PAY_STRCT_UP_RANGE,
PAY_STRCT_MID_RANGE, 
SLTYP,    
SLREG,
SLGRP,
SLLVL,
Effective_date,
 PK_DELETED
  
 from
(
select PAY_STRCT_CODE,Pay_strct_name ,PAY_STRCT_LW_RANGE, 
PAY_STRCT_UP_RANGE, 
SLTYP,    
SLREG,
SLGRP,
SLLVL,
Effective_date,
BEGDAT_CONCAT,
 PAY_STRCT_CODE||PAY_STRCT_LW_RANGE||PAY_STRCT_UP_RANGE||PAY_STRCT_MID_RANGE||SLTYP||SLREG||SLGRP||SLLVL||BEGDAT_CONCAT Compare_String,
 PK_DELETED,
  PAY_STRCT_MID_RANGE,
  SLREF
  from (
select distinct
MOLGA||''|''||SLTYP||''|''||SLREG||''|''||SLGRP||''|''||SLLVL PAY_STRCT_CODE,
MOLGA||''-''||SLTYP||''-''||SLREG||''-''||SLGRP||''-''||SLLVL Pay_strct_name,
to_char(to_number(ltrim(rtrim(SLMIN))))   PAY_STRCT_LW_RANGE,
to_char(to_number(ltrim(rtrim(SLMAX))))  PAY_STRCT_UP_RANGE ,
to_char(to_number(ltrim(rtrim(SLref))))  PAY_STRCT_MID_RANGE,
SLTYP,    
SLREG,
SLGRP,
SLLVL,
to_char(BEGDA,''yyyymmddhh24miss'') BEGDAT_CONCAT,
to_char(BEGDA,''yyyy-mm-dd'')||'' 00:00:00'' Effective_date,
SLREF,
''N'' PK_DELETED
from
mdmetl.STAGE_SO_T710)  
)
Where not exists
(Select compare_stng from 
( select 
p.PAY_STRCT_CODE||to_char(p.PAY_STRCT_LW_RANGE)||to_char(p.PAY_STRCT_UP_RANGE)||
to_char(p.PAY_STRCT_MID_RANGE)||p.PAY_TYPE_CODE||p.PAY_AREA_CODE||p.PAY_GRP_CODE||p.PAY_LEV_CODE||to_char(p.START_DATE,''yyyymmddhh24miss'') as Compare_Stng 
from  whsusr.REF_CUR_PAY_STRCT@MDMP.world@WHSUSR p
where p.PAY_STRCT_DELETED=''N'' )  b

where compare_string = compare_stng ) order by 1', 
    'C', 'STAGE_SO_T710', 21, 'N', 'CUR_PAY_STRCT');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, SP_REF_STRING1, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_EMP_SUB_GRP_DEL', 'T503K', 'SP_DETECT_DELTA', 'SELECT REF_CUR_EMP_SUB_GRP.EMP_SUB_GRP_ID  , ''Y'' AS DEL_FLAG
FROM
 WHSUSR.REF_CUR_EMP_SUB_GRP@MDMP.WORLD@WHSUSR
WHERE REF_CUR_EMP_SUB_GRP.EMP_SUB_GRP_DELETED<>''Y''', 
    'SELECT DISTINCT LTRIM(RTRIM(a.persk)) as PERSK , ''Y'' AS DEL_FLAG
FROM MDMETL.stage_so_t503t c,  MDMETL.stage_so_t503t b,MDMETL.stage_so_t503k a
WHERE a.persk = b.persk (+) and nvl(b.sprsl (+),''Z'') = ''E''
AND a.persk = c.persk (+) and nvl(c.sprsl (+),''Z'') = ''F''', 'C', 'STAGE_SO_T503K', 28, 
    'Y', 'CUR_EMP_SUB_GRP_DEL');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_PRSN_SHARP_LOAD', 'PA0709', 'SP_MULE_PRSN_SHARP_LOAD', 
    'C', 'STAGE_SO_PA0709', 3, 'Y', 'CUR_PRSN_SHARP');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_PRSN_FIN_SHARP_LOAD', 'PA2001', 'SP_MULE_FIN_SHARP_LOAD', 
    'C', 'STAGE_SO_PA2001', 7, 'Y', 'CUR_PRSN_FIN_SHARP');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_PRSN_DRV_LIC_LOAD', 'PA0185', 'SP_MULE_PRSN_DRV_LIC_LOAD', 
    'C', 'STAGE_SO_PA0185', 34, 'N', 'CUR_PRSN_DRV_LIC');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME, TEMP_TBL_QUERY)
 Values
   ('ABI_MULE_PRSN_DRV_LIC_DEL', 'PA0016', 'SP_MULE_PRSN_DRV_LIC_DEL', 
    'C', 'STAGE_SO_PA0016', 35, 'Y', 'CUR_PRSN_DRV_LIC_DEL', 'Select * from %%table_name%% order by PRSN_ID
asc');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_PRSN_ADDR_SHARP_DEL', 'PA0105', 'SP_MULE_PRSN_ADDR_SHARP_DEL', 
    'C', 'STAGE_SO_PA0105', 37, 'Y', 'CUR_PRSN_ADDR_SHARP_DEL');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, SP_REF_STRING1, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_HR_MU_DEL', 'ZXXP_ADDRESS', 'SP_DETECT_DELTA', 'SELECT REF_CUR_HR_MU.HR_MU_CODE, ''Y'' as del_flag
FROM
 WHSUSR.REF_CUR_HR_MU@MDMP.WORLD@WHSUSR 
WHERE
 REF_CUR_HR_MU.HR_MU_DELETED <> ''Y''', 
    'SELECT STAGE_SO_ZXXP_LOCOD.MARKETUNIT as MARKETUNIT, ''Y'' as del_flag FROM MDMETL.STAGE_SO_ZXXP_LOCOD where sprsl = ''E'' and molga in (''07'',''10'')', 'C', 'STAGE_SO_ZXXP_ADDRESS', 10, 
    'Y', 'CUR_HR_MU_DEL');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME, TEMP_TBL_QUERY)
 Values
   ('ABI_MULE_EMP_SHARP_LOAD', 'PA0041', 'SP_MULE_EMP_SHARP_LOAD', 
    'C', 'STAGE_SO_PA0041', 41, 'N', 'CUR_EMP_SHARP', 'Select EMP_PERNR ,  EMP_NAME   ,  EMP_STAT_CODE_REF ,  EMP_NO  ,  HR_PCTRY_CODE_REF  ,  EMP_HIRE_DATE,  EMP_TERM_DATE,  EMP_HIRE_DATE_ORIG ,  EMP_WORK_EMAIL  ,
  EMP_CNTC_END_DATE  ,  EMP_WRK_PERM_DATE  ,  PRSN_ID_REF,  POS_ID_REF ,  EMP_NO_AP_MDM_REF,  EMP_NO_AP_ERP_REF  ,  PAY_STRCT_CODE_REF ,  PRS_ACT_CODE_REF,
  PRS_ACT_RSN_CODE_REF  ,  EMP_GRP_ID_REF  ,  EMP_SUB_GRP_ID_REF ,  TAX_REG_CODE_REF,  HR_PSA_CODE_REF ,  PAY_ZBB_COST_CODE_REF ,  EMP_ASSIDUITY,
  EMP_SENIORITY,  EMP_SENIORITY_1_DATE  ,  EMP_SENIORITY_2_DATE  ,  EMP_VAC_QUOTA,  EMP_START_DATE  , EMP_STAFF_PCT,  DELETED , AEDTM_C from %%table_name%% order by EMP_PERNR,
AEDTM asc | Select * from %%table_name%% order by EMP_PERNR');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME, TEMP_TBL_QUERY)
 Values
   ('ABI_MULE_PRSN_FIN_SHARP_DEL', 'PA0208', 'SP_MULE_FIN_SHARP_DEL', 
    'C', 'STAGE_SO_PA0208', 16, 'Y', 'CUR_PRSN_FIN_SHARP_DEL', 'Select * from %%table_name%% order by PRSN_ID');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, SP_REF_STRING1, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_PAY_LEV_LOAD', 'V_T001', 'SP_DETECT_DELTA', 'SELECT  distinct sllvl, ''N'' AS DEL_FLAG
FROM  MDMETL.stage_so_v_t710
WHERE  sysdate BETWEEN begda AND endda
And sllvl is not null', 
    'SELECT REF_CUR_PAY_LEV.PAY_LEV_CODE as PAY_LEV_CODE,
REF_CUR_PAY_LEV.PAY_LEV_DELETED as PAY_LEV_DELETED
  FROM WHSUSR.REF_CUR_PAY_LEV@MDMP.WORLD@WHSUSR WHERE REF_CUR_PAY_LEV.PAY_LEV_DELETED=''N''', 'W', 'STAGE_SO_V_T001', 17, 
    'Y', 'CUR_PAY_LEV');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, SP_REF_STRING1, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_PAY_TYPE_DEL', 'V_T503Z', 'SP_DETECT_DELTA', 'SELECT REF_CUR_PAY_TYPE.PAY_TYPE_CODE , ''Y'' AS DEL_FLAG
FROM
 WHSUSR.REF_CUR_PAY_TYPE @MDMP.WORLD@WHSUSR
WHERE
 REF_CUR_PAY_TYPE.PAY_TYPE_DELETED <> ''Y''', 
    'SELECT  distinct sltyp AS SLTYP , ''Y'' AS DEL_FLAG
FROM  MDMETL.stage_so_v_t710a
WHERE  sysdate BETWEEN begda AND endda
And sltyp is not null', 'C', 'STAGE_SO_V_T503Z', 20, 
    'Y', 'CUR_PAY_TYPE_DEL');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, SP_REF_STRING1, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_PAY_STRCT_DEL', 'PA0000', 'SP_DETECT_DELTA', 'SELECT DISTINCT REF_CUR_PAY_STRCT.PAY_STRCT_CODE , ''Y'' AS DEL_FLAG
FROM
 WHSUSR.REF_CUR_PAY_STRCT @MDMP.WORLD@WHSUSR
WHERE
 REF_CUR_PAY_STRCT.PAY_STRCT_DELETED<>''Y''', 
    'select MOLGA||''|''||SLTYP||''|''||SLREG||''|''||SLGRP||''|''||SLLVL as PAY_STRCT_CODE, ''Y'' AS DEL_FLAG
from MDMETL.STAGE_SO_T710', 'C', 'STAGE_SO_PA0000', 22, 
    'Y', 'CUR_PAY_STRCT_DEL');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, SP_REF_STRING1, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_EMP_SHARP_DEL', 'PA0002', 'SP_DETECT_DELTA', 'SELECT DISTINCT REF_CUR_EMP_SHARP.EMP_PERNR ,''Y'' AS DEL_FLAG
FROM
 WHSUSR.REF_CUR_EMP_SHARP @MDMP.WORLD@WHSUSR
WHERE
 REF_CUR_EMP_SHARP.EMP_DELETED <> ''Y''', 
    'SELECT STAGE_SO_PA0002.PERNR as PERNR,''Y''  FROM MDMETL.STAGE_SO_PA0002 where trunc(sysdate) between begda and endda', 'C', 'STAGE_SO_PA0002', 40, 
    'N', 'CUR_EMP_SHARP_DEL');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_PA0001', 'PA0001', 'SP_FILENAME', 
    'C', 'STAGE_SO_PA0001', 54, 'N', 'CUR_FILENAME');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, SP_REF_STRING1, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_ORG_UNIT_LOAD', 'hrp1000', 'SP_DETECT_DELTA', 'Select distinct 
x.objid,
x.stext,
case when y.objid is not null then  x.sobid
else null end o_sobid,
''N''  del_flag    from (
SELECT         
    objid
    ,stext
    ,sobid
FROM     (
SELECT     a.objid
    ,NVL(a.stext,''NO VALUE'')    stext
    ,b.sobid    
FROM     MDMETL.stage_so_hrp1000
        a
    ,MDMETL.stage_so_hrp1001
        b
WHERE     b.objid = a.objid
AND     b.otype = ''O''
AND     b.plvar = ''01''
AND     b.rsign = ''A''
AND     b.relat = ''002''
AND     a.plvar = ''01''
AND     a.langu = ''E''
AND     a.otype = ''O''
AND     trunc(sysdate) BETWEEN a.begda AND a.endda
AND     trunc(sysdate) BETWEEN b.begda AND b.endda
UNION ALL
SELECT     a.objid
    ,NVL(a.stext,''NO VALUE'')    stext
    ,null
FROM     MDMETL.stage_so_hrp1000
        a
WHERE     a.plvar = ''01''
AND     a.langu = ''E''
AND     a.otype = ''O''
AND     trunc(sysdate) BETWEEN a.begda AND a.endda
AND     NOT EXISTS (
        SELECT      ''x''
        FROM     MDMETL.stage_so_hrp1001
        b
        WHERE     b.objid = a.objid
AND     trunc(sysdate) BETWEEN b.begda AND b.endda
AND     b.otype = ''O''
AND     b.plvar = ''01''
AND     b.rsign = ''A''
AND     b.relat = ''002''
)
)
CONNECT BY PRIOR objid = sobid
START WITH (sobid IS null 
OR sobid NOT IN
(SELECT objid
FROM MDMETL.stage_so_hrp1000
)) 
) x,  MDMETL.stage_so_hrp1000 y  where  x.sobid = y. objid  (+)', 
    'select
ORG_UNIT_CODE,
ORG_UNIT_NAME,
ORG_UNIT_CODE_REF,
ORG_UNIT_DELETED

FROM REF_CUR_ORG_UNIT@MDMP.WORLD@WHSUSR', 'W', 'STAGE_SO_HRP1000', 1, 
    'Y', 'CUR_ORG_UNIT');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, SP_REF_STRING1, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_ORG_UNIT_DEL', 'HRP1001', 'SP_DETECT_DELTA', 'SELECT REF_CUR_ORG_UNIT.ORG_UNIT_CODE ,''Y'' as del_flag
FROM
 WHSUSR.REF_CUR_ORG_UNIT@MDMP.WORLD@WHSUSR
WHERE
 REF_CUR_ORG_UNIT.ORG_UNIT_DELETED <> ''Y''', 
    'SELECT  /*+ FIRST_ROWS */ objid as OBJID,''Y'' as DEL_FLAG
FROM  (
SELECT  b.sobid, a.objid
FROM  MDMETL.stage_so_hrp1000  a
 , MDMETL.stage_so_hrp1001  b
WHERE  b.objid = a.objid
AND  b.otype = ''O''
AND  b.plvar = ''01''
AND  b.rsign = ''A''
AND  b.relat = ''002''
AND  a.plvar = ''01''
AND  a.langu = ''E''
AND  a.otype = ''O''
AND  trunc(sysdate) BETWEEN a.begda AND a.endda
AND  trunc(sysdate) BETWEEN b.begda AND b.endda
UNION ALL
SELECT  null, a.objid
FROM   MDMETL.stage_so_hrp1000  a
WHERE  a.plvar = ''01''
AND  a.langu = ''E''
AND  a.otype = ''O''
AND  trunc(sysdate) BETWEEN a.begda AND a.endda
AND  NOT EXISTS (
  SELECT   ''x''
  FROM   MDMETL.stage_so_hrp1001  b
  WHERE  b.objid = a.objid
AND  trunc(sysdate) BETWEEN b.begda AND b.endda
AND  b.otype = ''O''
AND  b.plvar = ''01''
AND  b.rsign = ''A''
AND  b.relat = ''002''
)
)
CONNECT BY PRIOR objid = sobid
-------------------------------------------------------
--START WITH sobid IS null
-------------------------------------------------------
START WITH (sobid IS null OR objid in (''90000059'',''90000089''))




/* FROM REF_CUR_ORG_UNIT@MDMP.WORLD@WHSUSR*/', 'C', 'STAGE_SO_HRP1001', 2, 
    'Y', 'CUR_ORG_UNIT_DEL');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME, TEMP_TBL_QUERY)
 Values
   ('ABI_MULE_PRSN_SHARP_DEL', 'PA0008', 'SP_MULE_PRSN_SHARP_DEL', 
    'C', 'STAGE_SO_PA0008', 4, 'Y', 'CUR_PRSN_SHARP_DEL', 'Select PRSN_ID,''Y'' from %%table_name%% order by PRSN_ID
asc');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, SP_REF_STRING1, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_PAY_ZBB_COST_LOAD', 'CSKT', 'SP_DETECT_DELTA', 'Select distinct cskt.KOSTL as KOSTL, cskt.LTEXT as LTEXT,''N'' AS DEL_FLAG
from MDMETL.STAGE_SO_CSKT cskt, MDMETL.STAGE_SO_T500P t500p
where cskt.KOKRS = t500p.PERSA
and cskt.SPRAS = ''E''
and t500p.MOLGA in (''07'',''10'')', 
    'SELECT REF_CUR_PAY_ZBB_COST.PAY_ZBB_COST_CODE as PAY_ZBB_COST_CODE, REF_CUR_PAY_ZBB_COST.PAY_ZBB_COST_NAME as PAY_ZBB_COST_NAME,  REF_CUR_PAY_ZBB_COST.PAY_ZBB_COST_DELETED as PAY_ZBB_COST_DELETED FROM WHSUSR.REF_CUR_PAY_ZBB_COST@MDMP.WORLD@WHSUSR', 'W', 'STAGE_SO_CSKT', 23, 
    'Y', 'CUR_PAY_ZBB_COST');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_POS_SHARP_IT_PROF_LOAD', 'HRP9001', 'SP_STORE_SQUERY_IN_TEMP', 'select POS_ID , profile_id as IT_SERV_PROF_CODE_REF, ''N'' AS POS_DELETED, UPPER(TO_CHAR(BEGDA, ''DD-MON-YYYY'')) || '' 00:00:00'' as EFFECTIVE_DATE from
(SELECT   DISTINCT LTRIM(RTRIM(OBJID)) as objid
        ,LTRIM(RTRIM(PROFILE_ID)) as profile_id
        ,BEGDA
FROM     mdmetl.stage_so_HRP9001
WHERE    otype = ''S''
ORDER BY 1, 3) s,
(SELECT POS_ID FROM whsusr.REG_CUR_POS_SHARP@MDMP.world@WHSUSR  ) r
where
r.pos_id = s.objid', 
    'C', 'STAGE_SO_HRP9001', 38, 'N', 'CUR_POS_IT_PROF');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_T528T', 'T528T', 'SP_FILENAME', 
    'C', 'STAGE_SO_T528T', 44, 'N', 'CUR_FILENAME');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_T5K0P', 'T5K0P', 'SP_FILENAME', 
    'C', 'STAGE_SO_T5K0P', 52, 'N', 'CUR_FILENAME');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_PRSN_PERS_SHARP_Load', 'PA0021', 'SP_MULE_PRSN_PERS_SHARP', 
    'C', 'STAGE_SO_PA0021', 5, 'Y', 'CUR_PRSN_PERS_SHARP');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME, TEMP_TBL_QUERY)
 Values
   ('ABI_MULE_PRSN_PERS_SHARP_DEL', 'PA2006', 'SP_MULE_PRSN_PERS_SHARP_DEL', 
    'C', 'STAGE_SO_PA2006', 6, 'Y', 'CUR_PRSN_PERS_SHARP_DEL', 'Select * from %%table_name%% order by PRSN_ID asc');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, SP_REF_STRING1, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_Mule_HR_MU_LOAD', 'ZXXP_LOCOD', 'SP_DETECT_DELTA', 'SELECT DISTINCT STAGE_SO_ZXXP_LOCOD.MARKETUNIT as HR_MU_CODE,''N'' as HR_MU_DELETED
FROM
 MDMETL.STAGE_SO_ZXXP_LOCOD 
WHERE
 sprsl = ''E'' and molga in (''07'',''10'')', 
    'SELECT REF_CUR_HR_MU.HR_MU_CODE as HR_MU_CODE, REF_CUR_HR_MU.HR_MU_DELETED as HR_MU_DELETED FROM WHSUSR.REF_CUR_HR_MU@MDMP.WORLD@WHSUSR where 
HR_MU_DELETED=''N''', 'C', 'STAGE_SO_ZXXP_LOCOD', 9, 
    'N', 'CUR_HR_MU');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_T500T', 'T500T', 'SP_FILENAME', 
    'C', 'STAGE_SO_T500T', 47, 'N', 'CUR_FILENAME');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, SP_REF_STRING1, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_EMP_GRP_DEL', 'T501', 'SP_DETECT_DELTA', 'SELECT REF_CUR_EMP_GRP.EMP_GRP_ID , ''Y'' del_flag
FROM
 WHSUSR.REF_CUR_EMP_GRP@MDMP.WORLD@WHSUSR
WHERE
 REF_CUR_EMP_GRP.EMP_GRP_DELETED<>''Y''', 
    'SELECT  LTRIM(RTRIM(a.persg)) as PERSG, ''Y'' del_flag
FROM MDMETL.stage_so_t501t c, MDMETL.stage_so_t501t b, MDMETL.stage_so_t501 a
WHERE a.persg = b.persg (+) and nvl(b.sprsl (+),''Z'') = ''E''', 'C', 'STAGE_SO_T501', 12, 
    'Y', 'CUR_EMP_GRP_DEL');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, SP_REF_STRING1, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_EMP_SUB_GRP_LOAD', 'T503T', 'SP_DETECT_DELTA', 'SELECT DISTINCT LTRIM(RTRIM(a.persk)) as PERSK
       ,LTRIM(RTRIM(NVL(b.ptext, ''NO VALUE''))) as PTEXT
    ,LTRIM(RTRIM(NVL(c.ptext, ''NO VALUE''))) as PTEXT_FR,
    ''N'' as EMP_SUB_GRP_DELETED
FROM MDMETL.stage_so_t503t c, MDMETL.stage_so_t503t b, MDMETL.stage_so_t503k a
WHERE a.persk = b.persk (+) and nvl(b.sprsl (+),''Z'') = ''E''
AND a.persk = c.persk (+) and nvl(c.sprsl (+),''Z'') = ''F''', 
    'SELECT REF_CUR_EMP_SUB_GRP.EMP_SUB_GRP_ID as EMP_SUB_GRP_ID,REF_CUR_EMP_SUB_GRP.EMP_SUB_GRP_NAME as EMP_SUB_GRP_NAME,
 REF_CUR_EMP_SUB_GRP.EMP_SUB_GRP_FR_NAME as EMP_SUB_GRP_FR_NAME ,
     ''N'' as EMP_SUB_GRP_DELETED
      FROM WHSUSR.REF_CUR_EMP_SUB_GRP@MDMP.WORLD@WHSUSR', 'C', 'STAGE_SO_T503T', 13, 
    'Y', 'CUR_EMP_SUB_GRP');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, SP_REF_STRING1, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_PRS_ACT_DEL', 'PA0461', 'SP_DETECT_DELTA', 'SELECT DISTINCT REF_CUR_PRS_ACT.PRS_ACT_CODE , ''Y'' AS DEL_FLAG
FROM
 WHSUSR.REF_CUR_PRS_ACT@MDMP.WORLD@WHSUSR 
WHERE
 REF_CUR_PRS_ACT.PRS_ACT_DELETED<>''Y''', 
    'select distinct t1.MASSN as MASSN, ''Y'' AS DEL_FLAG
from MDMETL.STAGE_SO_T530T t1, MDMETL.STAGE_SO_T530T t2
where t1.massn = t2.massn
and t1.sprsl = ''E''
and (t1.massn like (''Z%'') or t1.massn like (''D%''))
and t2.sprsl = ''F''
and (t2.massn like (''Z%'') or t1.massn like (''D%''))', 'C', 'STAGE_SO_PA0461', 14, 
    'Y', 'CUR_PRS_ACT_DEL');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, SP_REF_STRING1, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_PAY_LEV_DEL', 'HRP1007', 'SP_DETECT_DELTA', 'SELECT REF_CUR_PAY_LEV.PAY_LEV_CODE , ''Y'' AS DEL_FLAG
FROM
WHSUSR.REF_CUR_PAY_LEV@MDMP.WORLD@WHSUSR 
WHERE
 REF_CUR_PAY_LEV.PAY_LEV_DELETED <> ''Y''', 
    'SELECT  distinct sllvl AS SLLVL, ''Y'' AS DEL_FLAG
FROM  MDMETL.stage_so_v_t710
WHERE  sysdate BETWEEN begda AND endda
And sllvl is not null', 'C', 'STAGE_SO_HRP1007', 18, 
    'Y', 'CUR_PAY_LEV_DEL');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, SP_REF_STRING1, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_PAY_TYPE_LOAD', 'HRP9002', 'SP_DETECT_DELTA', 'SELECT  distinct sltyp
 ,NVL(tartx, ''NO VALUE'') tartx, ''N'' AS DEL_FLAG
FROM  MDMETL.stage_so_v_t710a
WHERE  sysdate BETWEEN begda AND endda
And sltyp is not null', 
    ' SELECT  REF_CUR_PAY_TYPE.PAY_TYPE_CODE as PAY_TYPE_CODE, REF_CUR_PAY_TYPE.PAY_TYPE_NAME as PAY_TYPE_NAME,
 REF_CUR_PAY_TYPE.PAY_TYPE_DELETED as PAY_TYPE_DELETED 
   FROM WHSUSR.REF_CUR_PAY_TYPE@MDMP.WORLD@WHSUSR WHERE REF_CUR_PAY_TYPE.PAY_TYPE_DELETED=''N''', 'C', 'STAGE_SO_HRP9002', 19, 
    'Y', 'CUR_PAY_TYPE');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_T527X', 'T527X', 'SP_FILENAME', 
    'C', 'STAGE_SO_T527X', 43, 'N', 'CUR_FILENAME');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_T529U', 'T529U', 'SP_FILENAME', 
    'C', 'STAGE_SO_T529U', 46, 'N', 'CUR_FILENAME');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_ZXXP_TEAMID', 'ZXXP_TEAMID', 'SP_FILENAME', 
    'C', 'STAGE_SO_ZXXP_TEAMID', 50, 'N', 'CUR_FILENAME');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_POS_SHARP_STATUS_LOAD', 'HRP1007', 'SP_STORE_SQUERY_IN_TEMP', 'SELECT  DISTINCT R.POS_ID
        ,DECODE(ltrim(rtrim(status)) , ''0'',''0'',''2'',''1'') AS POS_STATUS
        ,''N'' POS_DELETED
        , UPPER(TO_CHAR(BEGDA, ''DD-MON-YYYY'')) || '' 00:00:00'' AS EFFECTIVE_DATE 
FROM  MDMETL.stage_so_hrp1007 S, WHSUSR.REG_CUR_POS_SHARP@MDMP.WORLD@WHSUSR R
WHERE S.otype = ''S''
AND R.POS_ID =  ltrim(rtrim(S.OBJID))
ORDER BY 1, 3', 
    'C', 'STAGE_SO_HRP1007', 84, 'N', 'CUR_POS_STATUS');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, SP_REF_STRING1, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_PAY_AREA_LOAD', 'V_T710A', 'SP_DETECT_DELTA', 'SELECT  distinct slreg
 ,NVL(tgbtx, ''NO VALUE'') tgbtx, ''N'' AS DEL_FLAG 
FROM  MDMETL.stage_so_v_t710a
WHERE  sysdate BETWEEN begda AND endda
And slreg is not null', 
    'SELECT REF_CUR_PAY_AREA.PAY_AREA_CODE as PAY_AREA_CODE,REF_CUR_PAY_AREA.PAY_AREA_NAME as PAY_AREA_NAME 
, REF_CUR_PAY_AREA.PAY_AREA_DELETED as PAY_AREA_DELETED
 FROM REF_CUR_PAY_AREA@MDMP.WORLD@WHSUSR where REF_CUR_PAY_AREA.PAY_AREA_DELETED=''N''', 'C', 'STAGE_SO_V_T710A', 24, 
    'N', 'CUR_PAY_AREA');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, SP_REF_STRING1, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_PAY_AREA_DEL', 'V_T5U0P', 'SP_DETECT_DELTA', 'SELECT REF_CUR_PAY_AREA.PAY_AREA_CODE  , ''Y'' AS DEL_FLAG
FROM
 WHSUSR.REF_CUR_PAY_AREA @MDMP.WORLD@WHSUSR
WHERE
 REF_CUR_PAY_AREA.PAY_AREA_DELETED <> ''Y''', 
    'SELECT  distinct slreg AS SLREG  , ''Y'' AS DEL_FLAG
FROM  MDMETL.stage_so_v_t710a
WHERE  sysdate BETWEEN begda AND endda
And slreg is not null', 'C', 'STAGE_SO_V_T5U0P', 25, 
    'Y', 'CUR_PAY_AREA_DEL');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, SP_REF_STRING1, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_PAY_ZBB_COST_DEL', 'T500P', 'SP_DETECT_DELTA', 'SELECT REF_CUR_PAY_ZBB_COST.PAY_ZBB_COST_CODE ,''Y'' as del_flag
FROM
whsusr.REF_CUR_PAY_ZBB_COST @MDMP.WORLD@WHSUSR
WHERE REF_CUR_PAY_ZBB_COST.PAY_ZBB_COST_DELETED <> ''Y''', 
    'Select cskt.KOSTL as KOSTL,''Y''
from MDMETL.STAGE_SO_CSKT cskt, MDMETL.STAGE_SO_T500P t500p
where cskt.KOKRS = t500p.PERSA
and cskt.SPRAS = ''E''
and t500p.MOLGA in (''07'',''10'')', 'C', 'STAGE_SO_T500P', 39, 
    'Y', 'CUR_PAY_ZBB_COST_DEL');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_T5U0P', 'T5U0P', 'SP_FILENAME', 
    'C', 'STAGE_SO_T5U0P', 53, 'N', 'CUR_FILENAME');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME, TEMP_TBL_QUERY)
 Values
   ('ABI_MULE_POS_SHARP_TV_LOAD  ', 'HRP1005', 'SP_MULE_POS_SHARP_TV_LOAD', 
    'C', 'STAGE_SO_HRP1005', 42, 'Y', 'CUR_POS_SHARP_TV', 'Select * from %%table_name%% order by 
POS_ID asc');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, SP_REF_STRING1, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_PROV_UPDATE_LOAD', 'INPUT_FILENAME', 'SP_DETECT_DELTA', 'SELECT PROV_ID,
       PROV_NAME || '', '' || CTRY_ABBR AS PROV_PROVINCE,
         mdmetl.mdm_cnvt.clean_string(PROV_NAME, ''Y'') AS PROV_NAME,
         mdmetl.mdm_cnvt.clean_string (PROV_FR_NAME, ''Y'') AS PROV_FR_NAME
  FROM (SELECT b.CTRY_ABBR, a.PROV_ID, a.PROV_NAME, a.PROV_FR_NAME 
FROM whsusr.REG_CUR_PROV@MDMP.world@WHSUSR A,  whsusr.REG_CUR_CTRY@MDMP.world@WHSUSR B 
WHERE A.CTRY_ID = B.CTRY_ID)', 
    'select PROV_ID, PROV_PROVINCE, PROV_NAME, PROV_FR_NAME from WHSUSR.REF_CUR_PROV@MDMP.WORLD@WHSUSR', 'C', 'REG_CUR_PROV', 63, 
    'N', 'CUR_PROV_UPDATE');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_LAB_USI_UOM', 'LAB_USI_UOM', 'SP_MULE_STOCK_ITEM_UOM_LD_STG', 
    'C', 'STG_LAB_USI_UOM', 79, 'N', 'CUR_LAB_USI_UOM');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT)
 Values
   ('ABI_MULE_OUT_STOCK_ITEM_SAP_ALT_UOM', 'OUT_STOCK_ITEM_SAP_ALT_UOM', 'SP_MULE_OUT_STOCK_SAP_ALT_UOM', 
    'C', 'reg_cur_sap_uom', 85, 'N');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, SP_REF_STRING1, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_wl_LAB_SPA_USI_LOAD', 'LAB_SPA_USI', 'SP_MULE_STOCK_ITEM_LOAD_STAGE', 'SELECT  USI_SAP_ITEM_ID,
       LABATT_FLAG,
       USI_DESC,
       USI_UPC_CODE,
       USI_NOTES,
       USI_TYPE_CODE,
       USI_STATUS_CODE,
       MAT_GRP_CODE,
       PRD_TYP_ID,
       USI_BASE_UOM,
       TO_CHAR (USI_UNIT_VOLUME) AS O_USI_UNIT_VOLUME,
       USI_UNIT_VOLUME_UOM,
       TO_CHAR (USI_ITEM_WEIGHT_GR) AS O_USI_ITEM_WEIGHT_GR,
       USI_ITEM_WEIGHT_GR_UOM,
       TO_CHAR (USI_ITEM_WEIGHT_NET) AS O_USI_ITEM_WEIGHT_NET,
       USI_ITEM_WEIGHT_NET_UOM,
       TO_CHAR (USI_LENGTH) AS O_USI_LENGTH,
       TO_CHAR (USI_WIDTH) AS O_USI_WIDTH,
       TO_CHAR (USI_HEIGHT) AS O_USI_HEIGHT,
       USI_MEASURE_UOM,
       INV_ITEM_FLAG,
       STOCKBL_ITEM_FLAG,
       TO_CHAR (USI_UNITS_PER_PALLET) AS O_USI_UNITS_PER_PALLET,
       TO_CHAR (USI_UNITS_PER_TIER) AS O_USI_UNITS_PER_TIER,
       TO_CHAR (USI_UNITS_PER_LIFT) AS O_USI_UNITS_PER_LIFT       
  FROM MDMETL.STG_LAB_SPA_USI@MDMP.WORLD@MULE_MDMETL', 
    '025', 'C', 'STG_LAB_SPA_USI', 59, 
    'N', 'CUR_LAB_SPA_USI');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, SP_REF_STRING1, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_wl_LAB_SBA_USI_LOAD ', 'LAB_SBA_USI', 'SP_MULE_STOCK_ITEM_LOAD_STAGE', 'SELECT  USI_SAP_ITEM_ID,
       LABATT_FLAG,
       USI_DESC,
       USI_UPC_CODE,
       USI_NOTES,
       USI_TYPE_CODE,
       USI_STATUS_CODE,
       MAT_GRP_CODE,
       PRD_TYP_ID,
       USI_BASE_UOM,
       TO_CHAR (USI_UNIT_VOLUME) AS O_USI_UNIT_VOLUME,
       USI_UNIT_VOLUME_UOM,
       TO_CHAR (USI_ITEM_WEIGHT_GR) AS O_USI_ITEM_WEIGHT_GR,
       USI_ITEM_WEIGHT_GR_UOM,
       TO_CHAR (USI_ITEM_WEIGHT_NET) AS O_USI_ITEM_WEIGHT_NET,
       USI_ITEM_WEIGHT_NET_UOM,
       TO_CHAR (USI_LENGTH) AS O_USI_LENGTH,
       TO_CHAR (USI_WIDTH) AS O_USI_WIDTH,
       TO_CHAR (USI_HEIGHT) AS O_USI_HEIGHT,
       USI_MEASURE_UOM,
       INV_ITEM_FLAG,
       STOCKBL_ITEM_FLAG,
       TO_CHAR (USI_UNITS_PER_PALLET) AS O_USI_UNITS_PER_PALLET,
       TO_CHAR (USI_UNITS_PER_TIER) AS O_USI_UNITS_PER_TIER,
       TO_CHAR (USI_UNITS_PER_LIFT) AS O_USI_UNITS_PER_LIFT
         FROM MDMETL.STG_LAB_SBA_USI@MDMP.WORLD@MULE_MDMETL', 
    '019', 'C', 'STG_LAB_SBA_USI', 55, 
    'N', 'CUR_LAB_SBA_USI');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, SP_REF_STRING1, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_wl_LAB_RAW_USI_LOAD', 'LAB_RAW_USI', 'SP_MULE_STOCK_ITEM_LOAD_STAGE', 'SELECT  USI_SAP_ITEM_ID,
       LABATT_FLAG,
       USI_DESC,
       USI_UPC_CODE,
       USI_NOTES,
       USI_TYPE_CODE,
       USI_STATUS_CODE,
       MAT_GRP_CODE,
       PRD_TYP_ID,
             USI_BASE_UOM,
       TO_CHAR (USI_UNIT_VOLUME) AS O_USI_UNIT_VOLUME,
       USI_UNIT_VOLUME_UOM,
       TO_CHAR (USI_ITEM_WEIGHT_GR) AS O_USI_ITEM_WEIGHT_GR,
       USI_ITEM_WEIGHT_GR_UOM,
       TO_CHAR (USI_ITEM_WEIGHT_NET) AS O_USI_ITEM_WEIGHT_NET,
       USI_ITEM_WEIGHT_NET_UOM,
       TO_CHAR (USI_LENGTH) AS O_USI_LENGTH,
       TO_CHAR (USI_WIDTH) AS O_USI_WIDTH,
       TO_CHAR (USI_HEIGHT) AS O_USI_HEIGHT,
       USI_MEASURE_UOM,
       INV_ITEM_FLAG,
       STOCKBL_ITEM_FLAG,
       TO_CHAR (USI_UNITS_PER_PALLET) AS O_USI_UNITS_PER_PALLET,
       TO_CHAR (USI_UNITS_PER_TIER) AS O_USI_UNITS_PER_TIER,
       TO_CHAR (USI_UNITS_PER_LIFT) AS O_USI_UNITS_PER_LIFT 
  FROM MDMETL.STG_LAB_RAW_USI@MDMP.WORLD@MULE_MDMETL', 
    '002', 'C', 'STG_LAB_RAW_USI', 56, 
    'N', 'CUR_LAB_RAW_USI');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, SP_REF_STRING1, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_wl_LAB_POS_USI_LOAD', 'LAB_POS_USI', 'SP_MULE_STOCK_ITEM_LOAD_STAGE', 'SELECT  USI_SAP_ITEM_ID,
       LABATT_FLAG,
       USI_DESC,
       USI_UPC_CODE,
       USI_NOTES,
       USI_TYPE_CODE,
       USI_STATUS_CODE,
       MAT_GRP_CODE,
       PRD_TYP_ID,
       USI_BASE_UOM,
       TO_CHAR (USI_UNIT_VOLUME) AS O_USI_UNIT_VOLUME,
       USI_UNIT_VOLUME_UOM,
       TO_CHAR (USI_ITEM_WEIGHT_GR) AS O_USI_ITEM_WEIGHT_GR,
       USI_ITEM_WEIGHT_GR_UOM,
       TO_CHAR (USI_ITEM_WEIGHT_NET) AS O_USI_ITEM_WEIGHT_NET,
       USI_ITEM_WEIGHT_NET_UOM,
       TO_CHAR (USI_LENGTH) AS O_USI_LENGTH,
       TO_CHAR (USI_WIDTH) AS O_USI_WIDTH,
       TO_CHAR (USI_HEIGHT) AS O_USI_HEIGHT,
       USI_MEASURE_UOM,
       INV_ITEM_FLAG,
       STOCKBL_ITEM_FLAG,
       TO_CHAR (USI_UNITS_PER_PALLET) AS O_USI_UNITS_PER_PALLET,
       TO_CHAR (USI_UNITS_PER_TIER) AS O_USI_UNITS_PER_TIER,
       TO_CHAR (USI_UNITS_PER_LIFT) AS O_USI_UNITS_PER_LIFT
       FROM MDMETL.STG_LAB_POS_USI@MDMP.WORLD@MULE_MDMETL', 
    '023', 'C', 'STG_LAB_POS_USI', 58, 
    'N', 'CUR_LAB_POS_USI');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, SP_REF_STRING1, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_CTRY_UPDATE_LOAD', 'INPUT_FILENAME', 'SP_DETECT_DELTA', ' SELECT CTRY_ID, mdmetl.mdm_cnvt.clean_string(CTRY_NAME, ''Y'') as CTRY_NAME , mdmetl.mdm_cnvt.clean_string(CTRY_FR_NAME , ''Y'') as  CTRY_FR_NAME
FROM
 whsusr.REG_CUR_CTRY@MDMP.world@WHSUSR', 
    'select CTRY_ID, CTRY_NAME, CTRY_FR_NAME from WHSUSR.REF_CUR_CTRY@MDMP.WORLD@WHSUSR', 'C', 'REG_CUR_CTRY', 65, 
    'N', 'CUR_CTRY_UPDATE');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_PKG_PRD_LOAD', 'INPUT_FILENAME', 'SP_STORE_SQUERY_IN_TEMP', 'select MDMETL.MDM_SEQ.FETCH_PKG_PRD_ID AS PKG_PRD_ID, src.PRD_DESC, src.PRD_FDESC,   ''1'' IN_USE_FLAG,  src.brd_id, src.pkg_id , ''N'' PKG_PRD_DELETED
from( 
(SELECT DISTINCT
     u.brd_id AS BRD_ID
    ,u.pkg_id AS PKG_ID
    ,b.brd_desc||'' ''||p.pkg_desc AS    PRD_DESC
    ,b.brd_fdesc||'' ''||p.pkg_fdesc AS PRD_FDESC
FROM     WHSUSR.ref_cur_lab_pkg_usi@MDMP.WORLD@WHSUSR    u
        ,WHSUSR.reg_cur_brd@MDMP.WORLD@WHSUSR            b
        ,WHSUSR.reg_cur_pkg@MDMP.WORLD@WHSUSR            p
WHERE b.brd_id = u.brd_id
AND p.pkg_id = u.pkg_id
UNION ALL
SELECT DISTINCT
     u.brd_id AS BRD_ID
    ,u.pkg_id AS PKG_ID
    ,b.brd_desc||'' ''||p.pkg_desc AS    PRD_DESC
    ,b.brd_fdesc||'' ''||p.pkg_fdesc AS PRD_FDESC
FROM     WHSUSR.ref_cur_comp_pkg_usi@MDMP.WORLD@WHSUSR    u
        ,WHSUSR.reg_cur_brd@MDMP.WORLD@WHSUSR            b
        ,WHSUSR.reg_cur_pkg@MDMP.WORLD@WHSUSR           p
WHERE b.brd_id = u.brd_id
AND p.pkg_id = u.pkg_id
UNION ALL
SELECT         DISTINCT
     u.brd_id
    ,l.pkg_id
    ,b.brd_desc || '' '' || p.pkg_desc    PRD_DESC
    ,b.brd_fdesc || '' '' || p.pkg_fdesc    PRD_FDESC
FROM     WHSUSR.ref_cur_lab_loc_prd@MDMP.WORLD@WHSUSR        l
    ,WHSUSR.ref_cur_lab_pkg_usi@MDMP.WORLD@WHSUSR        u
    ,WHSUSR.reg_cur_brd@MDMP.WORLD@WHSUSR        b
    ,WHSUSR.reg_cur_pkg@MDMP.WORLD@WHSUSR       p
WHERE     b.brd_id = u.brd_id
AND     p.pkg_id = l.pkg_id
AND     u.usi_id = l.usi_id
AND     NOT EXISTS (
        SELECT     ''x''
        FROM     WHSUSR.ref_cur_lab_pkg_usi@MDMP.WORLD@WHSUSR    u1
        WHERE     u1.brd_id = u.brd_id
        AND     u1.pkg_id = l.pkg_id)) 
        ) src
        where not  exists         
        ( SELECT BRD_ID,
         PKG_ID
         , PKG_PRD_DESC, PKG_PRD_FDESC 
         FROM WHSUSR.REF_CUR_PKG_PRD@MDMP.WORLD@WHSUSR refn
where PKG_PRD_DELETED=''N''
and src.brd_id = refn.brd_id
and src.pkg_id = refn.pkg_id)', 
    'C', 'REF_CUR_COMP_PKG_USI', 66, 'N', 'CUR_PKG_PRD');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_LPRD_AI_LOAD', 'INPUT_FILENAME', 'SP_STORE_SQUERY_IN_TEMP', 'SELECT MDMETL.MDM_SEQ.FETCH_ANAL_ITEM_ID AS ANAL_ITEM_ID, LPPRD_KEY, BRD_ID
FROM (
SELECT LPPRD_KEY, NULL BRD_ID
FROM (
(SELECT LPPRD_KEY 
FROM WHSUSR.REF_CUR_LAB_LOC_PRD@MDMP.WORLD@WHSUSR 
UNION
SELECT LPPRD_KEY 
FROM WHSUSR.REF_CUR_COMP_LOC_PRD@MDMP.WORLD@WHSUSR)
MINUS
SELECT LPPRD_KEY AS LPPRD_KEY
FROM WHSUSR.REF_CUR_LPRD_AI@MDMP.WORLD@WHSUSR 
WHERE BRD_ID IS NULL
AND      ANAL_ITEM_EFF_DATE IS NULL)

UNION

(
(SELECT LP.LPPRD_KEY,
       UC.BRD_ID
FROM WHSUSR.REF_CUR_LAB_LOC_PRD@MDMP.WORLD@WHSUSR LP,
     WHSUSR.REF_CUR_USI_COMP@MDMP.WORLD@WHSUSR     UC
WHERE UC.USI_ID = LP.USI_ID
AND      UC.BRD_ID IS NOT NULL
AND      UC.PIC_INSERT_FLAG = ''false''
UNION ALL
SELECT CP.LPPRD_KEY,
       UC.BRD_ID
FROM WHSUSR.REF_CUR_COMP_LOC_PRD@MDMP.WORLD@WHSUSR CP,
     WHSUSR.REF_CUR_USI_COMP@MDMP.WORLD@WHSUSR     UC
WHERE UC.USI_ID = CP.USI_ID
AND      UC.BRD_ID IS NOT NULL
AND      UC.PIC_INSERT_FLAG = ''false'')
MINUS
SELECT  LPPRD_KEY AS LPPRD_KEY, BRD_ID AS BRD_ID      
FROM WHSUSR.REF_CUR_LPRD_AI@MDMP.WORLD@WHSUSR 
WHERE ANAL_ITEM_EFF_DATE IS NULL
)
)', 
    'C', 'REF_CUR_USI_COMP', 68, 'N', 'CUR_LPRD_AI');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, SP_REF_STRING1, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_wl_LAB_OTH_USI_LOAD', 'LAB_OTH_USI', 'SP_MULE_STOCK_ITEM_LOAD_STAGE', 'SELECT  USI_SAP_ITEM_ID,
       LABATT_FLAG,
       USI_DESC,
       USI_UPC_CODE,
       USI_NOTES,
       USI_TYPE_CODE,
       USI_STATUS_CODE,
       MAT_GRP_CODE,
       PRD_TYP_ID,
       USI_BASE_UOM,
       TO_CHAR (USI_UNIT_VOLUME) AS O_USI_UNIT_VOLUME,
       USI_UNIT_VOLUME_UOM,
       TO_CHAR (USI_ITEM_WEIGHT_GR) AS O_USI_ITEM_WEIGHT_GR,
       USI_ITEM_WEIGHT_GR_UOM,
       TO_CHAR (USI_ITEM_WEIGHT_NET) AS O_USI_ITEM_WEIGHT_NET,
       USI_ITEM_WEIGHT_NET_UOM,
       TO_CHAR (USI_LENGTH) AS O_USI_LENGTH,
       TO_CHAR (USI_WIDTH) AS O_USI_WIDTH,
       TO_CHAR (USI_HEIGHT) AS O_USI_HEIGHT,
       USI_MEASURE_UOM,
       INV_ITEM_FLAG,
       STOCKBL_ITEM_FLAG,
       TO_CHAR (USI_UNITS_PER_PALLET) AS O_USI_UNITS_PER_PALLET,
       TO_CHAR (USI_UNITS_PER_TIER) AS O_USI_UNITS_PER_TIER,
       TO_CHAR (USI_UNITS_PER_LIFT) AS O_USI_UNITS_PER_LIFT       
  FROM MDMETL.STG_LAB_OTH_USI@MDMP.WORLD@MULE_MDMETL', 
    '010', 'C', 'STG_LAB_OTH_USI', 60, 
    'N', 'CUR_LAB_OTH_USI');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, SP_REF_STRING1, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_CITY_UPDATE_LOAD', 'INPUT_FILENAME', 'SP_DETECT_DELTA', 'SELECT CITY_ID,
       mdmetl.mdm_cnvt.clean_string(CITY_NAME, ''Y'') as CITY_NAME,
        mdmetl.mdm_cnvt.clean_string (CITY_NAME, ''Y'') || '', '' || DECODE (PROV_ABBR,
                  CTRY_ABBR, CTRY_ABBR,
                  PROV_ABBR || '', '' || CTRY_ABBR)
          AS CITY_MUNICIPALITY
  FROM (  SELECT a.CITY_ID, a.CITY_NAME, b.CTRY_ABBR, c.PROV_ABBR 
               FROM whsusr.REG_CUR_CITY@MDMP.world@WHSUSR A, whsusr.REG_CUR_CTRY@MDMP.world@WHSUSR B, whsusr.REG_CUR_PROV@MDMP.world@WHSUSR C
                where B.CTRY_ID=C.CTRY_ID and C.PROV_ID=A.PROV_ID)', 
    'SELECT  CITY_ID, CITY_NAME,  CITY_MUNICIPALITY  FROM whsusr.REF_CUR_CITY@MDMP.world@WHSUSR', 'C', 'REG_CUR_CITY', 64, 
    'N', 'CUR_CITY_UPDATE');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, SP_REF_STRING1, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_LAB_PKG_USI_LOAD', 'LAB_PKG_USI', 'SP_MULE_STOCK_ITEM_LOAD_STAGE', 'SELECT  USI_SAP_ITEM_ID,
       LABATT_FLAG,
       USI_DESC,
       USI_UPC_CODE,
       USI_NOTES,
       USI_TYPE_CODE,
       USI_STATUS_CODE,
       MAT_GRP_CODE,
       PRD_TYP_ID,
        USI_BASE_UOM,
       TO_CHAR (USI_UNIT_VOLUME) AS O_USI_UNIT_VOLUME,
       USI_UNIT_VOLUME_UOM,
       TO_CHAR (USI_ITEM_WEIGHT_GR) AS O_USI_ITEM_WEIGHT_GR,
       USI_ITEM_WEIGHT_GR_UOM,
       TO_CHAR (USI_ITEM_WEIGHT_NET) AS O_USI_ITEM_WEIGHT_NET,
       USI_ITEM_WEIGHT_NET_UOM,
       TO_CHAR (USI_LENGTH) AS O_USI_LENGTH,
       TO_CHAR (USI_WIDTH) AS O_USI_WIDTH,
       TO_CHAR (USI_HEIGHT) AS O_USI_HEIGHT,
       USI_MEASURE_UOM,
       INV_ITEM_FLAG,
       STOCKBL_ITEM_FLAG,
       TO_CHAR (USI_UNITS_PER_PALLET) AS O_USI_UNITS_PER_PALLET,
       TO_CHAR (USI_UNITS_PER_TIER) AS O_USI_UNITS_PER_TIER,
       TO_CHAR (USI_UNITS_PER_LIFT) AS O_USI_UNITS_PER_LIFT,
       USI_PLAN_ITEM_FLAG,
       GBL_PRD_HIER_ID,
       GBL_SUB_BRAND_CODE,
       GBL_CONT_MAT_CODE,
       USI_QC_PRC_SEG_CODE
        FROM MDMETL.STG_LAB_PKG_USI@MDMP.WORLD@MULE_MDMETL', 
    '001', 'C', 'STG_LAB_PKG_USI', 26, 
    'N', 'CUR_LAB_PKG_USI');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_IT_SERV_PROF_BDGT_LOAD', 'INPUT_FILENAME', 'SP_STORE_SQUERY_IN_TEMP', 'SELECT s.IT_SERV_BDGT_CODE || ''|'' || s.IT_SERV_PROF_CODE         AS IT_SERV_PROF_BDGT_CODE,
       s.IT_SERV_BDGT_CODE AS IT_SERV_BDGT_CODE,
       s.IT_SERV_PROF_CODE AS IT_SERV_PROF_CODE,
       s.IT_SERV_BDGT_NAME || '' for '' || s.IT_SERV_PROF_NAME        AS IT_SERV_PROF_BDGT_NAME,
     ''0'' AS IT_SERV_PROF_BDGT_CA_BDGT,
     ''0'' AS IT_SERV_PROF_BDGT_US_BDGT,
       NVL2 (r.PARAMETER_VALUE_2,
             r.PARAMETER_VALUE_2,
             TO_CHAR (TRUNC (SYSDATE, r.PARAMETER_VALUE_1), ''DD-Mon-YYYY''))
          AS EFFECTIVE_DATE
  FROM (SELECT b.it_serv_bdgt_code as IT_SERV_BDGT_CODE,
       p.it_serv_prof_code as IT_SERV_PROF_CODE,
       b.it_serv_bdgt_name as IT_SERV_BDGT_NAME,
       p.it_serv_prof_name as IT_SERV_PROF_NAME
FROM WHSUSR.reg_cur_it_serv_prof@MDMP.WORLD@WHSUSR p
    , WHSUSR.reg_cur_it_serv_bdgt@MDMP.WORLD@WHSUSR b
WHERE NOT EXISTS (
        SELECT ''x''
        FROM WHSUSR.reg_cur_it_serv_prof_bdgt@MDMP.WORLD@WHSUSR pb
        WHERE pb.it_serv_prof_code=p.it_serv_prof_code
        AND pb.it_serv_bdgt_code=b.it_serv_bdgt_code)) s,
       (SELECT PARAMETER_TYPE,
               PARAMETER_NAME,
               PARAMETER_VALUE_1,
               PARAMETER_VALUE_2
          FROM MDMETL.MDM_CONTROL_PARAMETER) r
 WHERE r.PARAMETER_TYPE =''IT_SERV_PROF_BDGT''
       AND  r.PARAMETER_NAME = ''EFFECTIVE_DATE''', 
    'C', 'REG_CUR_IT_SERV_BDGT', 72, 'N', 'CUR_IT_SERV_PROF_BDGT');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, SP_REF_STRING1, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_AD_LOAD', 'INPUT_FILENAME', 'SP_DETECT_DELTA', 'SELECT STAGE_AD.AD_LAST_NAME, STAGE_AD.AD_FIRST_NAME, STAGE_AD.AD_NAME,
CASE WHEN SUBSTR(LTRIM(RTRIM(EMP_NO_REF)), 1, 1)  >=  ''0'' AND SUBSTR(LTRIM(RTRIM(EMP_NO_REF)), 1, 1) <= ''9''
THEN  LPAD(EMP_NO_REF, 6, ''0'')
ELSE null
END AS EMP_NO_REF, ''N'' AD_DELETED
FROM
 MDMETL.STAGE_AD', 
    ' SELECT  REF_CUR_AD.AD_LAST_NAME as AD_LAST_NAME, REF_CUR_AD.AD_FIRST_NAME as AD_FIRST_NAME, REF_CUR_AD.AD_NAME as AD_NAME, 
  REF_CUR_AD.EMP_NO as EMP_NO, REF_CUR_AD.AD_DELETED as AD_DELETED
   FROM WHSUSR.REF_CUR_AD@MDMP.WORLD@WHSUSR', 'C', 'STAGE_AD', 81, 
    'N', 'CUR_AD');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_RAW_AI_PH_LOAD', 'INPUT_FILENAME', 'SP_STORE_SQUERY_IN_TEMP', 'SELECT USI_ID, MDMETL.MDM_SEQ.FETCH_ANAL_ITEM_ID AS ANAL_ITEM_ID FROM ( 
SELECT DISTINCT USI_ID
FROM WHSUSR.REF_CUR_LAB_PH_USI@MDMP.WORLD@WHSUSR 
WHERE USI_TYPE_CODE <> ''????'' 
MINUS
SELECT USI_ID FROM WHSUSR.REF_CUR_RAW_AI@MDMP.WORLD@WHSUSR 
)', 
    'C', 'REF_CUR_LAB_PH_USI', 69, 'N', 'CUR_RAW_AI_PH');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_RAW_AI_POS_LOAD', 'INPUT_FILENAME', 'SP_STORE_SQUERY_IN_TEMP', 'SELECT USI_ID, MDMETL.MDM_SEQ.FETCH_ANAL_ITEM_ID AS ANAL_ITEM_ID FROM ( 
SELECT DISTINCT USI_ID
FROM WHSUSR.REF_CUR_LAB_POS_USI@MDMP.WORLD@WHSUSR 
WHERE USI_TYPE_CODE <> ''????'' 
MINUS
SELECT USI_ID FROM WHSUSR.REF_CUR_RAW_AI@MDMP.WORLD@WHSUSR 
)', 
    'C', 'REF_CUR_LAB_POS_USI', 70, 'N', 'CUR_RAW_AI_POS');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_RAW_AI_OTH_LOAD', 'INPUT_FILENAME', 'SP_STORE_SQUERY_IN_TEMP', 'SELECT USI_ID, MDMETL.MDM_SEQ.FETCH_ANAL_ITEM_ID AS ANAL_ITEM_ID FROM ( 
SELECT DISTINCT USI_ID
FROM WHSUSR.REF_CUR_LAB_OTH_USI@MDMP.WORLD@WHSUSR 
WHERE USI_TYPE_CODE <> ''????'' 
MINUS
SELECT USI_ID FROM WHSUSR.REF_CUR_RAW_AI@MDMP.WORLD@WHSUSR 
)', 
    'C', 'REF_CUR_LAB_OTH_USI', 71, 'N', 'CUR_RAW_AI_OTH');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_IT_SERV_PROF_ENT_LOAD', 'INPUT_FILENAME', 'SP_STORE_SQUERY_IN_TEMP', 'SELECT so.IT_SERV_CODE || ''|'' || so.IT_SERV_PROF_CODE           AS IT_SERV_PROF_ENT_CODE,
       so.IT_SERV_CODE AS IT_SERV_CODE,
       so.IT_SERV_PROF_CODE AS IT_SERV_PROF_CODE,
       so.IT_SERV_NAME || '' for '' || so.IT_SERV_PROF_NAME
          AS IT_SERV_PROF_ENT_NAME,
       ''No'' AS IT_SERV_PROF_ENT_VALUE,
       ''0'' AS IT_SERV_PROF_ENT_CA_BDGT,
       ''0'' AS IT_SERV_PROF_ENT_US_BDGT,
       NVL2 (re.PARAMETER_VALUE_2,
             re.PARAMETER_VALUE_2,
             TO_CHAR (TRUNC (SYSDATE, re.PARAMETER_VALUE_1), ''DD-Mon-YYYY''))
          AS EFFECTIVE_DATE
  FROM (SELECT p.it_serv_prof_code AS IT_SERV_PROF_CODE,
               s.it_serv_code AS IT_SERV_CODE,
               p.it_serv_prof_name AS IT_SERV_PROF_NAME,
               s.it_serv_name AS IT_SERV_NAME
          FROM whsusr.reg_cur_it_serv_prof@MDMP.WORLD@WHSUSR p, whsusr.reg_cur_it_serv@MDMP.WORLD@WHSUSR s
         WHERE NOT EXISTS
                      (SELECT ''x''
                         FROM whsusr.reg_cur_it_serv_prof_ent@MDMP.WORLD@WHSUSR e
                        WHERE e.it_serv_prof_code = p.it_serv_prof_code
                              AND e.it_serv_code = s.it_serv_code)) so,
       (SELECT PARAMETER_TYPE,
               PARAMETER_NAME,
               PARAMETER_VALUE_1,
               PARAMETER_VALUE_2
          FROM MDMETL.MDM_CONTROL_PARAMETER
          ) re
 WHERE re.PARAMETER_TYPE = ''IT_SERV_PROF_ENT''
               AND re.PARAMETER_NAME = ''EFFECTIVE_DATE''', 
    'C', 'REG_CUR_IT_SERV_PROF_ENT', 73, 'N', 'CUR_IT_SERV_PROF_ENT');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, SP_REF_STRING1, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_wl_LAB_PH_USI_LOAD ', 'LAB_PH_USI', 'SP_MULE_STOCK_ITEM_LOAD_STAGE', 'SELECT  USI_SAP_ITEM_ID,
       LABATT_FLAG,
       USI_DESC,
       USI_UPC_CODE,
       USI_NOTES,
       USI_TYPE_CODE,
       USI_STATUS_CODE,
       MAT_GRP_CODE,
       PRD_TYP_ID,
       USI_BASE_UOM,
       TO_CHAR (USI_UNIT_VOLUME) AS O_USI_UNIT_VOLUME,
       USI_UNIT_VOLUME_UOM,
       TO_CHAR (USI_ITEM_WEIGHT_GR) AS O_USI_ITEM_WEIGHT_GR,
       USI_ITEM_WEIGHT_GR_UOM,
       TO_CHAR (USI_ITEM_WEIGHT_NET) AS O_USI_ITEM_WEIGHT_NET,
       USI_ITEM_WEIGHT_NET_UOM,
       TO_CHAR (USI_LENGTH) AS O_USI_LENGTH,
       TO_CHAR (USI_WIDTH) AS O_USI_WIDTH,
       TO_CHAR (USI_HEIGHT) AS O_USI_HEIGHT,
       USI_MEASURE_UOM,
       INV_ITEM_FLAG,
       STOCKBL_ITEM_FLAG,
       TO_CHAR (USI_UNITS_PER_PALLET) AS O_USI_UNITS_PER_PALLET,
       TO_CHAR (USI_UNITS_PER_TIER) AS O_USI_UNITS_PER_TIER,
       TO_CHAR (USI_UNITS_PER_LIFT) AS O_USI_UNITS_PER_LIFT       
  FROM MDMETL.STG_LAB_PH_USI@MDMP.WORLD@MULE_MDMETL', 
    '021', 'C', 'STG_LAB_PH_USI', 77, 
    'N', 'CUR_LAB_PH_USI');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_RAW_AI_SBA_LOAD', 'INPUT_FILENAME', 'SP_STORE_SQUERY_IN_TEMP', 'SELECT USI_ID, MDMETL.MDM_SEQ.FETCH_ANAL_ITEM_ID AS ANAL_ITEM_ID FROM ( 
SELECT DISTINCT USI_ID
FROM WHSUSR.REF_CUR_LAB_SBA_USI@MDMP.WORLD@WHSUSR 
WHERE USI_TYPE_CODE <> ''????'' 
MINUS
SELECT USI_ID FROM WHSUSR.REF_CUR_RAW_AI@MDMP.WORLD@WHSUSR 
)', 
    'C', 'REF_CUR_LAB_SBA_USI', 78, 'N', 'CUR_RAW_AI_SBA');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_COMP_PKG_USI_UPDATE', 'INPUT_FILENAME', 'SP_STORE_SQUERY_IN_TEMP', '  SELECT DISTINCT y.USI_ID, y.PKG_PRD_ID
FROM  WHSUSR.REF_CUR_COMP_PKG_USI@MDMP.WORLD@WHSUSR y
 where  exists (
  select PKG_PRD_ID from (
  select PKG_PRD_ID from  WHSUSR.REF_CUR_COMP_PKG_USI@MDMP.WORLD@WHSUSR
  minus
   SELECT B.PKG_PRD_ID as PKG_PRD_ID FROM WHSUSR.REF_CUR_PKG_PRD@MDMP.WORLD@WHSUSR B, WHSUSR.REF_CUR_COMP_PKG_USI@MDMP.WORLD@WHSUSR a
  WHERE A.BRD_ID = B.BRD_ID
  AND A.PKG_ID = B.PKG_ID
  AND B.PKG_PRD_DELETED = ''N'' ) x
  where x.pkg_prd_id = y.pkg_prd_id
   )', 
    'C', 'REF_CUR_COMP_PKG_USI', 80, 'N', 'CUR_COMP_PKG_USI');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, SP_REF_STRING1, STATUS, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_AD_DEL', 'INPUT_FILENAME', 'SP_DETECT_DELTA', 'SELECT REF_CUR_AD.AD_NAME , ''Y'' AS AD_DELETED
FROM
  WHSUSR.REF_CUR_AD@MDMP.WORLD@WHSUSR 
WHERE
REF_CUR_AD.AD_DELETED <> ''Y''', 
    'SELECT STAGE_AD.AD_NAME as AD_NAME, ''Y'' DEL_FLAG FROM MDMETL.STAGE_AD', 'C', 82, 'N', 'CUR_AD_DEL');
Insert into TBL_ETL_ROUTE_DETAILS
   (INTERFACE_ID, FILE_NAME, SP_NAME, SP_STG_STRING1, STATUS, STG_TABLE, SEQUENCE_ID, IS_DEPENDENT, OUTPUT_FILE_NAME)
 Values
   ('ABI_MULE_RAW_AI_RM_LOAD', 'INPUT_FILENAME   ', 'SP_STORE_SQUERY_IN_TEMP', '  SELECT USI_ID, MDMETL.MDM_SEQ.FETCH_ANAL_ITEM_ID AS ANAL_ITEM_ID FROM ( 
SELECT DISTINCT USI_ID
FROM WHSUSR.REF_CUR_LAB_RAW_USI@MDMP.WORLD@WHSUSR 
WHERE USI_TYPE_CODE <> ''????'' 
MINUS
SELECT USI_ID FROM WHSUSR.REF_CUR_RAW_AI@MDMP.WORLD@WHSUSR 
)', 
    'C', 'REF_CUR_LAB_RAW_USI', 83, 'N', 'CUR_RAW_AI_RM');
COMMIT;
