SET DEFINE OFF;
--SQL Statement which produced this data:
--
--  SELECT 
--     ROWID, T.SEQUENCE_ID, T.INTERFACE_ID, T.PROJECT_NAME, 
--     T.PARTNER_NAME, T.IS_ETL, T.ENV
--  FROM IIW.TBL_DATA_MASTER T
--
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL, ENV)
 Values
   (92, 'IF_138', 'ABIWMS', 'WRS', 
    'N', 'TEST');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (4, 'ABI_MULE_ORG_UNIT_LOAD', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (32, 'ABI_MULE_EMP_GRP_LOAD', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (33, 'ABI_MULE_EMP_SUB_GRP_DEL', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (35, 'ABI_MULE_PAY_GRP_LOAD', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (36, 'ABI_MULE_PAY_GRP_DEL', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (37, 'ABI_MULE_POS_SHARP_DEL', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (38, 'ABI_MULE_POS_SHARP_LOAD', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (48, 'ABI_MULE_T527X', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (40, 'ABI_MULE_PRSN_DRV_LIC_DEL', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (41, 'ABI_MULE_PRSN_ADDR_SHARP_LOAD', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (50, 'ABI_MULE_T529T', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (52, 'ABI_MULE_T500T', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (57, 'ABI_MULE_T5K0P', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (59, 'ABI_MULE_PA0001', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (65, 'ABI_MULE_wl_LAB_SPA_USI_LOAD', 'ABI_MULE_STOCK_ITEMS', 'MDM_STOCKITEMS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (66, 'ABI_MULE_wl_LAB_OTH_USI_LOAD', 'ABI_MULE_STOCK_ITEMS', 'MDM_STOCKITEMS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (67, 'ABI_MULE_PHF_LOC_LOAD', 'ABI_MULE_PHF_LOC', 'MDM_PHF_LOC', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (69, 'ABI_MULE_CITY_UPDATE_LOAD', 'ABI_MULE_DAILY_CUR_LOAD', 'MDM_DAILYCURLOAD', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (93, 'IF_138', 'ABIWMS', 'WMS', 
    'N');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL, ENV)
 Values
   (101, 'IF_180', 'ABIWMS', 'WMS', 
    'N', 'TEST');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL, ENV)
 Values
   (96, 'IF_108', 'ABIWMS', 'WMS', 
    'N', 'TEST');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL, ENV)
 Values
   (97, 'IF_108', 'ABIWMS', 'WRS', 
    'N', 'TEST');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL, ENV)
 Values
   (98, 'IF_101', 'ABIWMS', 'WMS', 
    'N', 'TEST');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL, ENV)
 Values
   (99, 'IF_101', 'ABIWMS', 'WMS', 
    'N', 'TEST');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL, ENV)
 Values
   (100, 'IF_180', 'ABIWMS', 'SMT', 
    'N', 'TEST');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (8, 'ABI_MULE_PRSN_PERS_SHARP_DEL', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (58, 'ABI_MULE_T5U0P', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (11, 'ABI_MULE_PRSN_SHARP_LOAD', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (12, 'ABI_MULE_PRSN_PERS_SHARP_Load', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (13, 'ABI_MULE_ORG_UNIT_DEL', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (39, 'ABI_MULE_PRSN_DRV_LIC_LOAD', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (44, 'ABI_MULE_PAY_ZBB_COST_DEL', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (60, 'ABI_MULE_wl_LAB_SBA_USI_LOAD ', 'ABI_MULE_STOCK_ITEMS', 'MDM_STOCKITEMS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (61, 'ABI_MULE_wl_LAB_SBA_USI_LOAD ', 'ABI_MULE_STOCK_ITEMS', 'MDM_STOCKITEMS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (62, 'ABI_MULE_wl_LAB_RAW_USI_LOAD', 'ABI_MULE_STOCK_ITEMS', 'MDM_STOCKITEMS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (63, 'ABI_MULE_wl_LAB_PH_USI_LOAD ', 'ABI_MULE_STOCK_ITEMS', 'MDM_STOCKITEMS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (64, 'ABI_MULE_wl_LAB_POS_USI_LOAD', 'ABI_MULE_STOCK_ITEMS', 'MDM_STOCKITEMS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL, ENV)
 Values
   (102, 'IF_223', 'ABIWMS', 'WMS', 
    'N', 'TEST');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (7, 'ABI_MULE_PRSN_SHARP_DEL', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (15, 'ABI_MULE_PAY_AREA_LOAD', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (18, 'ABI_MULE_EMP_GRP_LOAD', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (25, 'ABI_MULE_PAY_LEV_DEL', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (26, 'ABI_MULE_PAY_TYPE_LOAD', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (28, 'ABI_MULE_PAY_STRCT_LOAD', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (29, 'ABI_MULE_PAY_STRCT_DEL', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (45, 'ABI_MULE_EMP_SHARP_DEL', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (47, 'ABI_MULE_POS_SHARP_TV_LOAD  ', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (68, 'ABI_MULE_PROV_UPDATE_LOAD', 'ABI_MULE_DAILY_CUR_LOAD', 'MDM_DAILYCURLOAD', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (70, 'ABI_MULE_CTRY_UPDATE_LOAD', 'ABI_MULE_DAILY_CUR_LOAD', 'MDM_DAILYCURLOAD', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (71, 'ABI_MULE_PKG_PRD_LOAD', 'ABI_MULE_DAILY_CUR_LOAD', 'MDM_DAILYCURLOAD', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (72, 'ABI_MULE_PKG_PRD_DEL', 'ABI_MULE_DAILY_CUR_LOAD', 'MDM_DAILYCURLOAD', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (73, 'ABI_MULE_LPRD_AI_LOAD', 'ABI_MULE_DAILY_CUR_LOAD', 'MDM_DAILYCURLOAD', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (74, 'ABI_MULE_RAW_AI_PH_LOAD', 'ABI_MULE_DAILY_CUR_LOAD', 'MDM_DAILYCURLOAD', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (75, 'ABI_MULE_RAW_AI_POS_LOAD', 'ABI_MULE_DAILY_CUR_LOAD', 'MDM_DAILYCURLOAD', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (76, 'ABI_MULE_RAW_AI_OTH_LOAD', 'ABI_MULE_DAILY_CUR_LOAD', 'MDM_DAILYCURLOAD', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (81, 'ABI_MULE_REF_CUR_LAB_LOC_PRD', 'ABI_MULE_DAILY_CUR_LOAD', 'MDM_DAILYCURLOAD', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (82, 'ABI_MULE_RAW_AI_SBA_LOAD', 'ABI_MULE_DAILY_CUR_LOAD', 'ABI_MULE_DAILY_CUR_LOAD', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL, ENV)
 Values
   (103, 'IF_223', 'ABIWMS', 'BDW', 
    'N', 'TEST');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (14, 'ABI_MULE_PRS_ACT_DEL', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (31, 'ABI_MULE_LAB_PKG_USI_LOAD', 'ABI_MULE_STOCK_ITEMS', 'MDM_STOCKITEMS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (46, 'ABI_MULE_EMP_SHARP_LOAD', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (6, 'Wl_PRSN_SHARP_LOAD', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (9, 'ABI_MULE_PRSN_FIN_SHARP_LOAD', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (16, 'ABI_Mule_HR_MU_LOAD', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (17, 'ABI_MULE_HR_MU_DEL', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (19, 'ABI_MULE_EMP_GRP_DEL', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (20, 'ABI_MULE_EMP_SUB_GRP_LOAD', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (43, 'ABI_MULE_POS_SHARP_IT_PROF_LOAD', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (22, 'ABI_MULE_PRSN_FIN_SHARP_DEL', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (23, 'ABI_MULE_PAY_AREA_DEL', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (24, 'ABI_MULE_PAY_LEV_LOAD', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (27, 'ABI_MULE_PAY_TYPE_DEL', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (30, 'ABI_MULE_PAY_ZBB_COST_LOAD', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (34, 'ABI_MULE_PRS_ACT_LOAD', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (42, 'ABI_MULE_PRSN_ADDR_SHARP_DEL', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (53, 'ABI_MULE_T005S', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (49, 'ABI_MULE_T528T', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (51, 'ABI_MULE_T529U', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (54, 'ABI_MULE_T500L', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (55, 'ABI_MULE_ZXXP_TEAMID', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (56, 'ABI_MULE_T591S', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (77, 'ABI_MULE_IT_SERV_PROF_BDGT_LOAD', 'ABI_MULE_DAILY_CUR_LOAD', 'MDM_DAILYCURLOAD', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (78, 'ABI_MULE_IT_SERV_PROF_ENT_LOAD', 'ABI_MULE_DAILY_CUR_LOAD', 'MDM_DAILYCURLOAD', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (79, 'ABI_MULE_REF_CUR_COMP_LOC_PRD', 'ABI_MULE_DAILY_CUR_LOAD', 'MDM_DAILYCURLOAD', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (80, 'REF_CUR_LAB_LOC_PRD', 'ABI_MULE_DAILY_CUR_LOAD', 'MDM_DAILYCURLOAD', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (85, 'ABI_MULE_LAB_USI_UOM', 'ABI_MULE_STOCK_ITEMS', 'MDM_STOCKITEMS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (86, 'ABI_MULE_RAW_AI_RM_LOAD', 'ABI_MULE_DAILY_CUR_LOAD', 'MDM_DAILYCURLOAD', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (87, 'ABI_MULE_COMP_PKG_USI_UPDATE', 'ABI_MULE_DAILY_CUR_LOAD', 'MDM_DAILYCURLOAD', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (88, 'ABI_MULE_AD_LOAD', 'ABI_MULE_DAILY_CUR_LOAD', 'MDM_DAILYCURLOAD', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (89, 'ABI_MULE_AD_DEL', 'ABI_MULE_DAILY_CUR_LOAD', 'MDM_DAILYCURLOAD', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (90, 'ABI_MULE_POS_SHARP_STATUS_LOAD', 'ABI_MULE_SHARP_OPS', 'MDM_SHARPOPS', 
    'Y');
Insert into TBL_DATA_MASTER
   (SEQUENCE_ID, INTERFACE_ID, PROJECT_NAME, PARTNER_NAME, IS_ETL)
 Values
   (91, 'ABI_MULE_OUT_STOCK_ITEM_SAP_ALT_UOM', 'ABI_MULE_STOCK_ITEMS', 'MDM_STOCKITEMS', 
    'Y');
COMMIT;
